### PR TITLE
Upgrade request dependency due to a security vulnerability

### PR DESCRIPTION
**Pull request by KevinBusse**
Fixes "Remote Memory Exposure", see https://snyk.io/vuln/npm:request:20160119

Signed-off-by: Kevin Busse <kevin.busse@gmail.com>

### CODE REVIEW

**Comment by rxaviers** [comment]
Thanks

**Comment by KevinBusse** [comment]
Can you also upload a new version to npm with that fix, please?

**Comment by rxaviers** [comment]
Sure, `0.2.4`.

**Comment by KevinBusse** [comment]
Thanks

**Pull request merged**
