### PR TITLE
Use axios to retrieve content via HTTP and remove request and request-progress

### PR DESCRIPTION
**Pull request by Vince-F**
Hello

Following a security investigation I saw that "request" was deprecated along with one of its dependency "har" which contains the package with vulnerability "ajv".

As a consequence rather than updating deprecated package which are unlikely to be updated in their main branch, I rewrote with "axios" package which is maintained.

By doing so however, we loose the progress report. On my side I felt it was not essential but this may be a blocking point.
I've done some tests, they were working but I didn't go in depth for all scenarios so I may be missing something.

### CODE REVIEW

**Comment by rxaviers** [comment]
Thank you

**Comment by rxaviers** [comment]
@Vince-F would you like to create a new PR to remove lib/progress.js?

**Comment by rxaviers** [comment]
Note to self...


cldr-data-npm before the change:

```
GET `https://github.com/unicode-cldr/cldr-core/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/36.0.0.zip`
  [========================================] 34737551/34737551 100% 0.0s
Received 33923K total.
Unpacking it into `./`
```

cldr-data-npm after the change:

```
GET `https://github.com/unicode-cldr/cldr-core/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/36.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/36.0.0.zip`
Unpacking it into `./`
```

**Comment by Vince-F** [comment]
> @Vince-F would you like to create a new PR to remove lib/progress.js?

Oh indeed sorry I was in a bit of a rush I forgot that. I'm adding that to my todo list I'll try to do this tonight or tomorrow.

**Comment by rxaviers** [comment]
No problem and thank you

**Pull request merged**
